server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

helloservice:
  ribbon:
    # not used by RestTemplate with ribbon-eureka
    #listOfServers: localhost:8081, localhost:8083
    #NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList

    # the eureka vipAddress of the target service (Disabled)
    DeploymentContextBasedVipAddresses: helloservice
